#!/bin/bash

# Install dotfile bin scripts.
# Pass the destination dir as an optional argument. Installs to $HOME by default.
#
# install/bin [DEST:$HOME]
#

set -e

DEST=$(readlink -f ${1:-$HOME})

DOTFILES=$(cd "$(dirname "$BASH_SOURCE")/.."; pwd -P)

function install_dest_bin {
    for src in $(find -H "$DOTFILES/bin" -maxdepth 1 -type f)
    do
        dst="$DEST/bin/$(basename "${src}")"
        if [ -L "$dst" ]; then
            echo Link "$dst" exists, skipping link
        elif [ -f "$dst" ]; then
            echo File "$dst" exists, skipping link
        else
            echo Linking "$dst"
            ln -s "$src" "$dst"
        fi
    done
}

install_dest_bin
