#!/bin/bash

# Install dotfile symlinks.
#
# Pass the destination dir as an optional argument. Installs to $HOME by default.
#
# install/links [DEST:$HOME]
#
# Compliments to https://github.com/holman/dotfiles/blob/master/script/bootstrap

set -e

DEST=$(readlink -f ${1:-$HOME})

mkdir -p "$DEST"

DOTFILES=$(cd "$(dirname "$BASH_SOURCE")/.."; pwd -P)

#
# Helpers
#

info () {
    printf "\r  [ \033[00;34m..\033[0m ] $1\n"
}

user () {
    printf "\r  [ \033[0;33m??\033[0m ] $1\n"
}

success () {
    printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
    printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
    echo ''
    exit
}

# Symbolic link with override/backup/skip prompt for existing files.
# Something is needed even for new users since .bashrc typically exists by default.
link_file () {
    local src=$1 dst=$2

    local overwrite= backup= skip=
    local action=

    if [ -f "$dst" -o -d "$dst" -o -L "$dst" ]
    then

        if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]
        then

            local currentSrc="$(readlink $dst)"

            if [ "$currentSrc" == "$src" ]
            then

                skip=true;

            else

                user "File already exists: $dst ($(basename "$src")), what do you want to do?\n\
        [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
                read -n 1 action

                case "$action" in
                    o )
                        overwrite=true;;
                    O )
                        overwrite_all=true;;
                    b )
                        backup=true;;
                    B )
                        backup_all=true;;
                    s )
                        skip=true;;
                    S )
                        skip_all=true;;
                    * )
                    ;;
                esac

            fi

        fi

        overwrite=${overwrite:-$overwrite_all}
        backup=${backup:-$backup_all}
        skip=${skip:-$skip_all}

        if [ "$overwrite" == "true" ]
        then
            rm -rf "$dst"
            success "removed $dst"
        fi

        if [ "$backup" == "true" ]
        then
            mv "$dst" "${dst}.backup"
            success "moved $dst to ${dst}.backup"
        fi

        if [ "$skip" == "true" ]
        then
            success "skipped $src"
        fi
    fi

    if [ "$skip" != "true" ]  # "false" or empty
    then
        ln -s "$src" "$dst"
        success "linked $src to $dst"
    fi
}

#
# Install the files
#

function install_links {
    local overwrite_all=${overwrite_all:-false}
    local backup_all=${backup_all:-false}
    local skip_all=${skip_all:-false}

    # TODO: support links in nested directories, preserving the relative path
    for src in $(find -H "$DOTFILES/links" -maxdepth 1 -type f -not -path '*/.git/*')
    do
        dst="$DEST/$(basename "${src}")"
        link_file "$src" "$dst"
    done
}

install_links
